### PR TITLE
Fix and improves download/get feature 

### LINKED ISSUE #19: Download doesn't work as expected
If you want to download an object, it will download the object, not the file/directories connected to it. This is a big problem due to the fact that the user is expecting to see a directory or a file, not something that has no extension.

### PR DESCRIPTION
**Pull request by koalalorenzo**
Closes #19

### CODE REVIEW

File: windows/Storage/fileIntegration.js [hunk 1]
```diff
@@ -50,33 +47,6 @@ export function addFilesPaths(paths){
...
 
 /**
- * This method will easily download from localhsot an Object, and save the file
- * into a specific path (dest).
- *
- * ToDo: Work with directories. (This saves only a file, not a directory)
- */
-export function saveFileToPath(objectID, dest){
-  return new Promise((success, failure) =>{
-    let url = `http://localhost:8080/ipfs/${objectID}`
```
Comment (koalalorenzo) [inline windows/Storage/fileIntegration.js]: This was just... I am so happy that I removed it!
iu
